version: '3.6'

networks:
    mytest:
        name: $DOCKER_NETWORK_NAME

services:
    $CC_LB_HOST_NAME:
        image: nginx:1.20.2-alpine
        container_name: $CC_LB_HOST_NAME
        volumes:
            - $NGINX_CONF:/etc/nginx/nginx.conf
        ports:
            - $CC_LB_PORT:$CC_LB_PORT
        networks:
            - mytest

