#!/bin/bash

. ./env.sh
. $ECERT_CA_ENV_FILE

HOST_VOLUME_BASE=$HOST_NODE_VOLUME
ADMIN_HOST_VOLUME=$HOST_VOLUME_BASE/users/$NODE_ADMIN_NAME

export FABRIC_CA_CLIENT_HOME=$ADMIN_HOST_VOLUME
export FABRIC_CA_CLIENT_MSPDIR=$FABRIC_CA_CLIENT_HOME/msp
export FABRIC_CA_CLIENT_TLS_CERTFILES=$ECERT_ROOT_CERT

fabric-ca-client identity list
