version: "3.6"

networks:
    emalidev:
        name: fabricnet 

services:
    stateapi:
      image: registry.gitlab.com/blockchain-project-emaliandzhengzhou/fabric-crud-setup/stateservice:$STATE_API_IMAGE_VERSION
      container_name: $STATE_API_CONTAINER_NAME
      volumes:
          - $STATE_API_CONFIG_FILE:/home/app/apiconfig.yaml
          - $STATE_API_LOG:/home/app/logs/event_server.log

          - $FABRIC_CONNECTION_FILE:/home/app/connection.yaml
          - $FABRIC_WALLET:/home/app/wallet
      ports:
          - $STATE_API_PORT:3001
      networks:
        - emalidev
