version: '3.6'

networks:
    mytest:
        name: $DOCKER_NETWORK_NAME

services:
  $CA_CONTAINER_NAME:
    image: hyperledger/fabric-ca:$FABRIC_CA_VERSION
    container_name: $CA_CONTAINER_NAME
    command: sh -c 'fabric-ca-server start -d -b $FABRIC_ECERT_CA_ADMIN:$FABRIC_ECERT_CA_PASSWD --cfg.affiliations.allowremove --cfg.identities.allowremove --port $FABRIC_ECERT_CA_PORT'
    environment:
      - TZ=$TIMEZONE
      - FABRIC_CA_HOME=$CA_CONTAINER_SERVER_HOME
      - FABRIC_CA_SERVER_CA_NAME=$CA_CSR_CN
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=$CA_CSR_CN
      - FABRIC_CA_SERVER_CSR_HOSTS=$CA_CSR_HOSTS
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
        # - $CA_SERVER_CONFIG_FILE:$CA_CONTAINER_SERVER_HOME/fabric-ca-server-config.yaml
      - $HOST_VOLUME_SERVER:$CA_CONTAINER_SERVER_HOME
      - $HOST_VOLUME_CLIENT:$CA_CONTAINER_CLIENT_HOME
    networks:
      - mytest
    ports:
      - $FABRIC_ECERT_CA_PORT:$FABRIC_ECERT_CA_PORT
