#!/bin/bash

. ./env.sh

SHARED_ENV=$HOST_SHARED_VOLUME/env.ecert

ECERT_ROOT_CERT=$HOST_VOLUME_SERVER/ca-cert.pem
FABRIC_CA_CLIENT_HOME=$HOST_VOLUME_CLIENT/ca/admin
FABRIC_CA_CLIENT_MSP=$FABRIC_CA_CLIENT_HOME/msp

# append tls info
echo " " > $SHARED_ENV
echo "export ECERT_CA_HOST_PORT=$ECERT_CA_HOST_PORT" >> $SHARED_ENV 
echo "export FABRIC_ECERT_CA_ADMIN=$FABRIC_ECERT_CA_ADMIN" >> $SHARED_ENV
echo "export FABRIC_ECERT_CA_PASSWD=$FABRIC_ECERT_CA_PASSWD" >> $SHARED_ENV
echo "export ECERT_ROOT_CERT=$ECERT_ROOT_CERT" >> $SHARED_ENV
echo "export ECERT_FABRIC_CA_CLIENT_HOME=$FABRIC_CA_CLIENT_HOME" >> $SHARED_ENV
echo "export ECERT_FABRIC_CA_CLIENT_MSP=$FABRIC_CA_CLIENT_MSP" >> $SHARED_ENV

