
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  fabricapp.test:
    external:
      name: fabricnet

services:

  explorerdb.fabricapp.test:
    image: leyle123456/explorer-db:$EXPLORER_VERSION
    container_name: explorerdb.fabricapp.test
    hostname: explorerdb.fabricapp.test
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - fabricapp.test

  explorer.fabricapp.test:
    image: leyle123456/explorer-web:$EXPLORER_VERSION
    container_name: explorer.fabricapp.test
    hostname: explorer.fabricapp.test
    environment:
      - DATABASE_HOST=explorerdb.fabricapp.test
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../users/orgadmin:/tmp/crypto/orgadmin
      - ./tls-ca-cert.pem:/tmp/crypto/tls/tls-ca-cert.pem
    ports:
      - 8080:8080
    depends_on:
      explorerdb.fabricapp.test:
        condition: service_healthy
    networks:
      - fabricapp.test
